/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Alternative;
import java.util.List;
import java.util.Map;

/**
 *
 * @author mauricio
 */
public class SolutionVisualizer extends javax.swing.JFrame {
  private List<Alternative> totalOrder;
  private Map<Alternative, List<Alternative>> partialPreorder;

  /**
   * Creates new form SolutionVisualizer
   */
  public SolutionVisualizer() {
    initComponents();
  }

  public SolutionVisualizer(
    List<Alternative> totalOrder,
    Map<Alternative, List<Alternative>> partialPreorder
  ) {
    this();
    this.partialPreorder = partialPreorder;
    this.totalOrder = totalOrder;
    setUp();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    totalOrderTextArea = new javax.swing.JTextArea();
    jLabel2 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    partialOrderTextArea = new javax.swing.JTextArea();
    jSeparator1 = new javax.swing.JSeparator();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Solución");

    jPanel1.setBackground(new java.awt.Color(50, 169, 50));

    jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
    jLabel1.setForeground(java.awt.Color.white);
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Solución");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
      jPanel1
    );
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(
          jLabel1,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          Short.MAX_VALUE
        )
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(
          jLabel1,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          68,
          Short.MAX_VALUE
        )
    );

    totalOrderTextArea.setEditable(false);
    totalOrderTextArea.setColumns(20);
    totalOrderTextArea.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
    totalOrderTextArea.setRows(5);
    jScrollPane1.setViewportView(totalOrderTextArea);

    jLabel2.setText("Ordenamiento total");

    jButton1.setText("Volver");
    jButton1.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton1ActionPerformed(evt);
        }
      }
    );

    jLabel3.setText("Ordenamiento parcial");

    partialOrderTextArea.setEditable(false);
    partialOrderTextArea.setColumns(20);
    partialOrderTextArea.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
    partialOrderTextArea.setRows(5);
    jScrollPane2.setViewportView(partialOrderTextArea);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(
                  jPanel1,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addComponent(
                  jScrollPane1,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  638,
                  Short.MAX_VALUE
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  layout
                    .createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton1)
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGroup(
                      layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addComponent(
                          jScrollPane2,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          628,
                          Short.MAX_VALUE
                        )
                        .addGroup(
                          layout
                            .createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(0, 0, Short.MAX_VALUE)
                        )
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(jSeparator1)
                )
            )
            .addContainerGap()
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(
              jPanel1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addComponent(jLabel2)
            .addGap(7, 7, 7)
            .addComponent(
              jScrollPane1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              173,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      jSeparator1,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      10,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  layout
                    .createSequentialGroup()
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                      15,
                      Short.MAX_VALUE
                    )
                    .addComponent(jLabel3)
                    .addGap(7, 7, 7)
                    .addComponent(
                      jScrollPane2,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      173,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addGap(18, 18, 18)
                )
            )
            .addComponent(jButton1)
            .addContainerGap()
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton1ActionPerformed
    this.setVisible(false);
  } //GEN-LAST:event_jButton1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java
        .util.logging.Logger.getLogger(SolutionVisualizer.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java
        .util.logging.Logger.getLogger(SolutionVisualizer.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java
        .util.logging.Logger.getLogger(SolutionVisualizer.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java
        .util.logging.Logger.getLogger(SolutionVisualizer.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {

        public void run() {
          new SolutionVisualizer().setVisible(true);
        }
      }
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JTextArea partialOrderTextArea;
  private javax.swing.JTextArea totalOrderTextArea;

  // End of variables declaration//GEN-END:variables

  private void setUp() {
    StringBuilder sb = new StringBuilder();
    sb.append(
      String.format(
        "%-15s%-16s%-16s%-16s\n",
        "Nombre",
        "Flujo neto",
        "Flujo positivo",
        "Fujo negativo"
      )
    );
    sb.append("------------------------------------------------------------\n");

    totalOrder
      .stream()
      .forEach(
        a -> {
          sb.append(
            String.format(
              "%-15s%-16.4f%-16.4f%-16.4f\n",
              a.getName(),
              a.getNetFlux(),
              a.getPosFlux(),
              a.getNegFlux()
            )
          );
        }
      );

    sb.append("------------------------------------------------------------\n");
    totalOrderTextArea.setText(sb.toString());

    StringBuilder sb1 = new StringBuilder();

    partialPreorder
      .entrySet()
      .stream()
      .forEach(
        e -> {
          e
            .getValue()
            .stream()
            .forEach(
              a -> {
                sb1.append(e.getKey().getName());
                sb1.append(" -> ");
                sb1.append(a.getName());
                sb1.append("\n");
              }
            );
        }
      );

    partialOrderTextArea.setText(sb1.toString());

    GraphVisual graphVisual = new GraphVisual(partialPreorder);
    graphVisual.pack();
    graphVisual.setVisible(true);
  }
}
